import { useState } from "react";
import GlobalContext from "./GlobalContext";

const GlobalProvider = ({ children }) => {
  const [coordinates, setCoordinates] = useState({
    lat: 28.7040592,
    lng: 77.10249019999999,
    place: "Delhi, India",
  });

  // state to show Search place or not
  const [searchPlace, setSearchPlace] = useState(false);

  // state to show login/signup page or not
  const [loginPage, setLoginPage] = useState(false);

  // state to choose which page to show login or signup
  const [isLogin, setIsLogin] = useState(true);

  const auth = JSON.parse(localStorage.getItem("loggedin"));

  // state to show is user logged in or not

  const [isLogged, setIsLogged] = useState(auth);

  // cart items will be placed in this arra

  const [cartItems, setCartItems] = useState([
    {
      info: {
        id: "70252297",
        name: "Chai",
        category: "Chai",
        imageId: "qg5mdf5n7slvgvggyf9f",
        inStock: 1,
        isVeg: 1,
        price: 1500,
        variants: {},
        variantsV2: {},
        maxAddons: -1,
        maxFreeAddons: -1,
        ribbon: {},
        itemBadge: {},
        badgesV2: {},
        ratings: {
          aggregatedRating: {
            rating: "4.3",
            ratingCount: "375 ratings",
            ratingCountV2: "375",
          },
        },
      },
      count: 4,
    },
    {
      info: {
        id: "1785041",
        name: "Veg Club Sandwich",
        category: "Sandwich Specials",
        description:
          "A generous amount of butter is smeared over the white bread followed by the secret dressings. It is then topped with exotic veggies and sandwich masala. The sandwich is then grilled in a toaster.",
        imageId: "plar1xnm504g8odhlupj",
        inStock: 1,
        isVeg: 1,
        price: 23000,
        variants: {},
        variantsV2: {},
        maxAddons: -1,
        maxFreeAddons: -1,
        addons: [
          {
            groupId: "43841585",
            groupName: "Add on",
            choices: [
              {
                id: "30341805",
                name: "Cold Coffee",
                price: 12000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
            ],
            maxAddons: -1,
            maxFreeAddons: -1,
          },
          {
            groupId: "23802346",
            groupName: "Add-ons",
            choices: [
              {
                id: "14477910",
                name: "Virgin Mojito",
                price: 11000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "2598289",
                name: "Cold Coffee (with Icecream ]",
                price: 18000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "2598277",
                name: "Kit Kat Shake",
                price: 14000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "2598269",
                name: "Chocolate Shake",
                price: 18000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "2598279",
                name: "Butterscotch Shake",
                price: 9000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "2598274",
                name: "Chocolate Belgium Shake",
                price: 17000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "2598265",
                name: "Chocolate Brownie Shake",
                price: 20000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "2598276",
                name: "Choco Chip Shake",
                price: 22000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "2598275",
                name: "Chocolate Hazelnut Shake",
                price: 22000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "2598281",
                name: "Blackcurrant Shake",
                price: 9000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "2598280",
                name: "Strawberry Shake",
                price: 9000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "2598272",
                name: "Oreo Shake",
                price: 12000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "2598271",
                name: "Choco Mud Shake",
                price: 12000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "2598282",
                name: "Vanilla Shake",
                price: 9000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
            ],
            maxAddons: 14,
            maxFreeAddons: -1,
          },
        ],
        ribbon: {},
        itemBadge: {},
        badgesV2: {},
        ratings: {
          aggregatedRating: {
            rating: "3.7",
            ratingCount: "410 ratings",
            ratingCountV2: "410",
          },
        },
      },
      count: 1,
    },
    {
      info: {
        id: "46378632",
        name: "Chocochips Ice Cream 500ml",
        category: "500 Ml Ice Creams",
        description:
          "Melt in mouth chocolate chips in every spoon. Truly, a decadent ice cream experience.  [Energy: 204 kcal, Allergen: milk,nuts, Carbohydrates: 24g]",
        imageId: "2791b4e0a62bbca96c37780572a27045",
        inStock: 1,
        isVeg: 1,
        price: 25424,
        finalPrice: 16900,
        variants: {},
        variantsV2: {},
        maxAddons: -1,
        maxFreeAddons: -1,
        ribbon: {
          text: "BESTSELLER",
          textColor: "#ffffff",
          topBackgroundColor: "#d53d4c",
          bottomBackgroundColor: "#b02331",
        },
        offerTags: [{}],
        itemBadge: {},
        badgesV2: {},
        ratings: {
          aggregatedRating: {
            rating: "4.6",
            ratingCount: "615 ratings",
            ratingCountV2: "615",
          },
        },
      },
      count: 3,
    },
    {
      info: {
        id: "47772437",
        name: "Crispy Chicken Club Burger",
        category: "Burgers",
        description:
          " Our Best Selling Burger ,Golden Crispy Chicken Patty Made With Secret Indian Spices, Creamy Mayo , Fresh Veggies With toasted cramlized bun.",
        imageId: "e4aeaa8e93604612a90f7677a768fef2",
        inStock: 1,
        price: 9900,
        variants: {},
        variantsV2: {},
        maxAddons: -1,
        maxFreeAddons: -1,
        addons: [
          {
            groupId: "24867301",
            groupName: "Select 1st Bun Options",
            choices: [
              {
                id: "25874144",
                name: "Regular",
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "25874145",
                name: "Wheat Bun",
                price: 1200,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
            ],
            maxAddons: 1,
            maxFreeAddons: -1,
            minAddons: 1,
          },
          {
            groupId: "24867305",
            groupName: "Make It A Meal - Regular",
            choices: [
              {
                id: "18073438",
                name: "Pepsi + Overloaded Cheesy Fries",
                price: 14900,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "18073437",
                name: "Pepsi + Tandoori Cheese Fries",
                price: 11900,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "18073436",
                name: "Pepsi + Sweet Potato Fries",
                price: 11900,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "18073435",
                name: "Pepsi + Chipotle Cheese Fries",
                price: 11900,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "18073434",
                name: "Pepsi + Crinkle Fries",
                price: 11900,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "25847469",
                name: "Pepsi + Paneer Cheesy Fries",
                price: 18900,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "25847470",
                name: "Pepsi + Chicken Cheesy Fries",
                price: 19900,
                inStock: 1,
                isEnabled: 1,
              },
            ],
            maxAddons: 1,
            maxFreeAddons: -1,
          },
          {
            groupId: "24867307",
            groupName: "Choice Of Beverage",
            choices: [
              {
                id: "18073459",
                name: "Caramel Latte",
                price: 10900,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "18073457",
                name: "Hot Chocolate",
                price: 7900,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "18073455",
                name: "Cappuccino",
                price: 8900,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "18073453",
                name: "Vanilla Latte",
                price: 10900,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "18073452",
                name: "Vanilla Cappuccino",
                price: 10900,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "18073451",
                name: "Hazelnut Cappuccino",
                price: 10900,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "18073450",
                name: "Caramel Cappuccino",
                price: 10900,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "18073448",
                name: "Cookies And Cream Shake",
                price: 20900,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "18073447",
                name: "Triple Chcolate Shake",
                price: 18900,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "18073446",
                name: "Strawberry Blunder Shake",
                price: 14900,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "18073445",
                name: "Iced Frappe",
                price: 10900,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "18073444",
                name: "Watermelon Ice Tea",
                price: 9900,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "18073443",
                name: "Ice Tea",
                price: 9900,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "18073442",
                name: "Lemon Ice Tea",
                price: 9900,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "18073441",
                name: "Spicy Mango Mojito",
                price: 9900,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "18073440",
                name: "Watermelon Shikanji",
                price: 9900,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "18073439",
                name: "Virgin Mojito",
                price: 9900,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
            ],
            maxAddons: 1,
            maxFreeAddons: -1,
          },
          {
            groupId: "56589840",
            groupName: "Add On",
            choices: [
              {
                id: "45970001",
                name: "Ketchup",
                price: 100,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
            ],
            maxAddons: 1,
            maxFreeAddons: -1,
          },
        ],
        ribbon: {
          text: "BESTSELLER",
          textColor: "#ffffff",
          topBackgroundColor: "#d53d4c",
          bottomBackgroundColor: "#b02331",
        },
        itemBadge: {},
        badgesV2: {},
        ratings: {
          aggregatedRating: {
            rating: "4.4",
            ratingCount: "2246 ratings",
            ratingCountV2: "2246",
          },
        },
      },
      count: 2,
    },
    {
      info: {
        id: "62455772",
        name: "Veg Masala Dosa",
        category: "Masala Dosa",
        description: "Serves 1",
        imageId: "s7veggctgjzilanedgul",
        inStock: 1,
        isVeg: 1,
        price: 15000,
        variants: {},
        variantsV2: {},
        itemAttribute: {
          vegClassifier: "VEG",
          portionSize: "Serves 1",
        },
        ribbon: {},
        showImage: true,
        itemBadge: {},
        badgesV2: {},
        ratings: {
          aggregatedRating: {
            rating: "3.8",
            ratingCount: "7 ratings",
            ratingCountV2: "7",
          },
        },
      },
      count: 1,
    },
    {
      info: {
        id: "110448579",
        name: 'Crowded House Pizza [Regular 7"]',
        category: 'REGULAR 7" PIZZAS | VEG [SERVES 1]',
        description:
          '[Regular 7" Serves 1] Extra Cheese | Paneer Cubes | Black Olive | Red Paprika | Golden Corn | Capsicum | Onion',
        imageId: "75d5bcd92212dd0e162ff53fae28cc23",
        inStock: 1,
        isVeg: 1,
        price: 31900,
        variants: {
          variantGroups: [
            {
              groupId: "32318663",
              name: "Choice of Crust",
              variations: [
                {
                  name: "Pan Tossed",
                  id: "100220712",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  name: "Cheese Blast",
                  price: 4900,
                  id: "100220709",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  name: "Thin Crust",
                  price: 2900,
                  id: "109096554",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
                {
                  name: "Thin Crust Cheese Blast",
                  price: 4900,
                  default: 1,
                  id: "109096553",
                  inStock: 1,
                  isVeg: 1,
                  isEnabled: 1,
                },
              ],
            },
          ],
        },
        variantsV2: {},
        maxAddons: -1,
        maxFreeAddons: -1,
        addons: [
          {
            groupId: "110911278",
            groupName: "Make it a FEAST?",
            choices: [
              {
                id: "100056045",
                name: "Choco Lava Cake + Pepsi Black [500 ml]",
                price: 12000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "101611328",
                name: "Choco Lava Cake + Pepsi [400 ml]",
                price: 12000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "100056047",
                name: "Choco Lava Cake + Lipton Ice Tea [250 ml]",
                price: 12000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "100056049",
                name: "Pack of Nachos + Pepsi Black [500 ml]",
                price: 8000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "101611327",
                name: "Pack of Nachos + Pepsi [400 ml]",
                price: 8000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "100056048",
                name: "Pack of Nachos + Lipton Ice Tea [250 ml]",
                price: 8000,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "100056044",
                name: "Choco Lava Cake + Pepsi [250 ml]",
                price: 12000,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "100056046",
                name: "Pack of Nachos + Pepsi [250 ml]",
                price: 8000,
                isVeg: 1,
                isEnabled: 1,
              },
            ],
            maxAddons: 5,
            maxFreeAddons: -1,
          },
          {
            groupId: "110911277",
            groupName: "Veg Toppings",
            choices: [
              {
                id: "100056061",
                name: "Paneer Cubes",
                price: 4900,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "100056057",
                name: "Mushrooms",
                price: 4900,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "100056058",
                name: "Black Olives",
                price: 3900,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "100056056",
                name: "Spicy Jalapenos",
                price: 3900,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "100056059",
                name: "Red Paprika",
                price: 3900,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "100056062",
                name: "Golden Corn",
                price: 3900,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "100056054",
                name: "Onion",
                price: 2900,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "100056055",
                name: "Tomato",
                price: 2900,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
              {
                id: "100056060",
                name: "Capsicum",
                price: 2900,
                inStock: 1,
                isVeg: 1,
                isEnabled: 1,
              },
            ],
            maxAddons: 6,
            maxFreeAddons: -1,
          },
        ],
        ribbon: {
          text: "BESTSELLER",
          textColor: "#ffffff",
          topBackgroundColor: "#d53d4c",
          bottomBackgroundColor: "#b02331",
        },
        offerTags: [
          {
            title: "50% OFF",
            subTitle: "USE TRYNEW",
            textColor: "#DB6742",
          },
        ],
        itemBadge: {},
        badgesV2: {},
        ratings: {
          aggregatedRating: {
            rating: "4.7",
            ratingCount: "42 ratings",
            ratingCountV2: "42",
          },
        },
      },
      count: 2,
    },
  ]);

  return (
    <GlobalContext.Provider
      value={{
        coordinates,
        setCoordinates,
        searchPlace,
        setSearchPlace,
        loginPage,
        setLoginPage,
        isLogin,
        setIsLogin,
        isLogged,
        setIsLogged,
        cartItems,
        setCartItems,
      }}
    >
      {children}
    </GlobalContext.Provider>
  );
};

export default GlobalProvider;
